services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/
    networks:
      - web
    restart: always

  demo-server:
    image: httpd:latest
    networks:
      - web

networks:
  web:
